name: Compare Latest Snapshots

on:
  workflow_dispatch: # or push / pull_request

jobs:
  compare-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get two latest snapshot files
        run: |
          readarray -t files < <(ls -t snapshots | head -n 2)
          latest1="${files[0]}"
          latest2="${files[1]}"
          echo "latest1=$latest1" >> $GITHUB_ENV
          echo "latest2=$latest2" >> $GITHUB_ENV

      - name: Compare snapshots and create branches
        run: |
          if ! diff -q "snapshots/${latest2}" "snapshots/${latest1}"; then
            branch_old="snapshot-old-$(date +%s)"
            branch_new="snapshot-new-$(date +%s)"
            
            # Create branch for older snapshot
            git checkout --orphan "$branch_old"
            git reset --hard
            mkdir snapshots
            cp "snapshots/${latest2}" snapshots/current.txt
            git add snapshots/current.txt
            git commit -m "Older snapshot"
            git push origin "$branch_old"
      
            # Switch back to main and create branch for newer snapshot
            git checkout main
            git checkout --orphan "$branch_new"
            git reset --hard
            mkdir snapshots
            cp "snapshots/${latest1}" snapshots/current.txt
            git add snapshots/current.txt
            git commit -m "Newer snapshot"
            git push origin "$branch_new"
      
            echo "DIFF_URL=https://github.com/${GITHUB_REPOSITORY}/compare/$branch_old...$branch_new" >> $GITHUB_ENV
            exit 1
          fi

      - name: Show GitHub diff link
        if: failure()
        run: |
          echo "$DIFF_URL"
