name: Compare Latest Snapshots

on:
  workflow_dispatch:

jobs:
  compare-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Parse URLs from YAML
        id: parse
        run: |
          echo "URL_IDS=$(yq '.ulta[].id' urls.yaml | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Compare snapshots per ID
        run: |
          for id in $URL_IDS; do
            dir="snapshots/ulta"
            files=($(ls -t $dir/${id}_*.html 2>/dev/null || true))
            if [ ${#files[@]} -ge 2 ]; then
              latest1="${files[0]}"
              latest2="${files[1]}"

              echo "Comparing $latest1 and $latest2"
              
              if ! diff -q "$latest2" "$latest1"; then
                branch_old="snapshot-${id}-old-$(date +%s)"
                branch_new="snapshot-${id}-new-$(date +%s)"

                cp "$latest2" /tmp/older_snapshot.txt
                cp "$latest1" /tmp/newer_snapshot.txt

                # Old snapshot branch
                git checkout --orphan "$branch_old"
                git reset --hard
                mkdir snapshots
                cp /tmp/older_snapshot.txt snapshots/current.txt
                git add snapshots/current.txt
                git commit -m "Older snapshot for $id"
                git push origin "$branch_old"

                # New snapshot branch
                git checkout main
                git checkout --orphan "$branch_new"
                git reset --hard
                mkdir snapshots
                cp /tmp/newer_snapshot.txt snapshots/current.txt
                git add snapshots/current.txt
                git commit -m "Newer snapshot for $id"
                git push origin "$branch_new"

                echo "Diff for $id: https://github.com/${GITHUB_REPOSITORY}/compare/$branch_old..$branch_new"
              fi
            else
              echo "Not enough snapshots for $id"
            fi
          done
