name: Diffy Scraper

# Trigger schedule
on:
  schedule:
    # Runs every 6 hours (UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch: # manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # 3. Build the Diffy scraper
      - name: Build Diffy
        run: go build -o diffy ./cmd/diffy

      # 4. Run the scraper
      - name: Run Diffy scraper
        run: ./diffy

      # 5. Commit and push snapshots
      - name: Commit and push snapshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update snapshots"
          git push
